yarnPath: ".yarn/releases/yarn-berry.js"

packageExtensions:
    "parcel-bundler@*":
        dependencies:
            "babel-types": "*"
    "@webpack-cli/package-utils@*":
        dependencies:
            "cross-spawn": "*"
    "awesome-worker-loader@*":
        dependencies:
            "core-js": "*"
